import React, { useState } from 'react';
import {
  X,
  List,
  Highlighter,
  Bookmark as BookmarkIcon,
  Download,
  Trash2,
  Clock,
  ExternalLink,
} from 'lucide-react';
import type { Book, BookChapter, Highlight, Bookmark } from '../types';
import { estimateReadingTimeMinutes } from '../services/bookParser';

interface TOCDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  chapters: BookChapter[];
  currentChapterIndex: number;
  onSelectChapter: (index: number) => void;
}

export const TOCDrawer: React.FC<TOCDrawerProps> = ({
  isOpen,
  onClose,
  chapters,
  currentChapterIndex,
  onSelectChapter,
}) => {
  if (!isOpen) return null;

  return (
    <aside
      className="fixed left-0 top-0 bottom-0 w-80 sm:w-96 bg-slate-900 border-r border-slate-800 z-40 shadow-2xl flex flex-col animate-in slide-in-from-left duration-200"
      aria-label="Table of Contents"
    >
      <div className="p-4 border-b border-slate-800 flex items-center justify-between bg-slate-950/60">
        <div className="flex items-center gap-2">
          <List className="w-4 h-4 text-amber-400" />
          <h3 className="text-sm font-semibold text-slate-100">Table of Contents</h3>
        </div>
        <button
          onClick={onClose}
          className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition"
        >
          <X className="w-5 h-5" />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-2 space-y-1">
        {chapters.map((ch, idx) => {
          const isActive = idx === currentChapterIndex;
          const readTime = estimateReadingTimeMinutes(ch.wordCount);
          return (
            <button
              key={ch.id || idx}
              onClick={() => {
                onSelectChapter(idx);
                onClose();
              }}
              className={`w-full text-left p-3 rounded-xl transition flex items-start justify-between gap-3 ${
                isActive
                  ? 'bg-amber-500/15 border border-amber-500/30 text-amber-300 font-medium'
                  : 'text-slate-300 hover:bg-slate-800/80 hover:text-slate-100'
              }`}
            >
              <div className="flex-1 min-w-0">
                <span className="text-xs line-clamp-2 leading-relaxed">{ch.title}</span>
                <span className="text-[10px] text-slate-400 block mt-1">
                  {ch.wordCount.toLocaleString()} words
                </span>
              </div>
              <div className="flex items-center gap-1 text-[11px] text-slate-400 shrink-0 mt-0.5">
                <Clock className="w-3 h-3 text-slate-400" />
                <span>{readTime}m</span>
              </div>
            </button>
          );
        })}
      </div>
    </aside>
  );
};

interface AnnotationsDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  highlights: Highlight[];
  bookmarks: Bookmark[];
  onDeleteHighlight: (id: string) => void;
  onDeleteBookmark: (id: string) => void;
  onJumpToBookmark: (bm: Bookmark) => void;
  bookTitle: string;
}

export const AnnotationsDrawer: React.FC<AnnotationsDrawerProps> = ({
  isOpen,
  onClose,
  highlights,
  bookmarks,
  onDeleteHighlight,
  onDeleteBookmark,
  onJumpToBookmark,
  bookTitle,
}) => {
  const [tab, setTab] = useState<'highlights' | 'bookmarks'>('highlights');

  if (!isOpen) return null;

  const exportAnnotationsToMarkdown = () => {
    let md = `# Annotations for ${bookTitle}\n*Generated by Lumina Reader*\n\n`;
    
    if (highlights.length > 0) {
      md += `## Highlights & Notes (${highlights.length})\n\n`;
      highlights.forEach((h, i) => {
        md += `> "${h.selectedText}"\n\n`;
        if (h.note) md += `*Note: ${h.note}*\n\n`;
        md += `---\n\n`;
      });
    }

    if (bookmarks.length > 0) {
      md += `## Bookmarks (${bookmarks.length})\n\n`;
      bookmarks.forEach((b) => {
        md += `- **${b.label}**: "${b.snippet}" (${new Date(b.createdAt).toLocaleDateString()})\n`;
      });
    }

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${bookTitle.replace(/\s+/g, '_')}_annotations.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const COLOR_CLASSES: Record<Highlight['color'], string> = {
    yellow: 'bg-amber-400/20 border-amber-400/40 text-amber-200',
    emerald: 'bg-emerald-400/20 border-emerald-400/40 text-emerald-200',
    sky: 'bg-sky-400/20 border-sky-400/40 text-sky-200',
    rose: 'bg-rose-400/20 border-rose-400/40 text-rose-200',
    amber: 'bg-orange-400/20 border-orange-400/40 text-orange-200',
  };

  return (
    <aside
      className="fixed left-0 top-0 bottom-0 w-80 sm:w-96 bg-slate-900 border-r border-slate-800 z-40 shadow-2xl flex flex-col animate-in slide-in-from-left duration-200"
      aria-label="Annotations & Highlights"
    >
      <div className="p-4 border-b border-slate-800 flex items-center justify-between bg-slate-950/60">
        <div className="flex items-center gap-2">
          <Highlighter className="w-4 h-4 text-amber-400" />
          <h3 className="text-sm font-semibold text-slate-100">Notebook & Annotations</h3>
        </div>
        <button
          onClick={onClose}
          className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition"
        >
          <X className="w-5 h-5" />
        </button>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-slate-800 bg-slate-950/40 p-1">
        <button
          onClick={() => setTab('highlights')}
          className={`flex-1 flex items-center justify-center gap-1.5 py-1.5 rounded-lg text-xs font-medium transition ${
            tab === 'highlights'
              ? 'bg-slate-800 text-amber-300 font-semibold shadow-xs'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          <Highlighter className="w-3.5 h-3.5" />
          <span>Highlights ({highlights.length})</span>
        </button>
        <button
          onClick={() => setTab('bookmarks')}
          className={`flex-1 flex items-center justify-center gap-1.5 py-1.5 rounded-lg text-xs font-medium transition ${
            tab === 'bookmarks'
              ? 'bg-slate-800 text-amber-300 font-semibold shadow-xs'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          <BookmarkIcon className="w-3.5 h-3.5" />
          <span>Bookmarks ({bookmarks.length})</span>
        </button>
      </div>

      {/* List */}
      <div className="flex-1 overflow-y-auto p-3 space-y-2.5">
        {tab === 'highlights' && (
          <>
            {highlights.length === 0 ? (
              <div className="text-center py-12 text-xs text-slate-400">
                Select any text while reading to highlight passages, attach thoughts, and export notes.
              </div>
            ) : (
              highlights.map((h) => (
                <div
                  key={h.id}
                  className={`p-3 rounded-xl border relative group text-xs leading-relaxed ${COLOR_CLASSES[h.color]}`}
                >
                  <p className="italic font-serif">"{h.selectedText}"</p>
                  {h.note && (
                    <p className="mt-2 pt-2 border-t border-white/10 text-[11px] text-slate-300 font-sans">
                      💬 {h.note}
                    </p>
                  )}
                  <div className="flex items-center justify-between mt-2 pt-1 text-[10px] text-slate-400 font-sans">
                    <span>{new Date(h.createdAt).toLocaleDateString()}</span>
                    <button
                      onClick={() => onDeleteHighlight(h.id)}
                      className="opacity-0 group-hover:opacity-100 p-1 text-slate-400 hover:text-rose-400 transition"
                      title="Delete highlight"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>
              ))
            )}
          </>
        )}

        {tab === 'bookmarks' && (
          <>
            {bookmarks.length === 0 ? (
              <div className="text-center py-12 text-xs text-slate-400">
                Click the bookmark icon or press <kbd className="font-mono text-amber-400">Ctrl+B</kbd> / <kbd className="font-mono text-amber-400">⌘+B</kbd> to save reading spots.
              </div>
            ) : (
              bookmarks.map((b) => (
                <div
                  key={b.id}
                  onClick={() => {
                    onJumpToBookmark(b);
                    onClose();
                  }}
                  className="p-3 rounded-xl bg-slate-800/80 border border-slate-700/80 hover:border-amber-500/50 cursor-pointer transition relative group"
                >
                  <div className="flex items-center justify-between text-xs font-medium text-amber-300 mb-1">
                    <span>{b.label}</span>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        onDeleteBookmark(b.id);
                      }}
                      className="opacity-0 group-hover:opacity-100 p-1 text-slate-400 hover:text-rose-400 transition"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>
                  <p className="text-[11px] text-slate-300 line-clamp-2 italic">"{b.snippet}"</p>
                  <span className="text-[10px] text-slate-400 block mt-1.5">
                    {new Date(b.createdAt).toLocaleDateString()}
                  </span>
                </div>
              ))
            )}
          </>
        )}
      </div>

      {/* Export footer */}
      {(highlights.length > 0 || bookmarks.length > 0) && (
        <div className="p-3 border-t border-slate-800 bg-slate-950/60">
          <button
            onClick={exportAnnotationsToMarkdown}
            className="w-full flex items-center justify-center gap-2 py-2 rounded-xl bg-slate-800 hover:bg-slate-750 text-slate-200 text-xs font-medium transition"
          >
            <Download className="w-3.5 h-3.5 text-amber-400" />
            <span>Export Notes as Markdown</span>
          </button>
        </div>
      )}
    </aside>
  );
};
